name: Update GitHub Activity

on:
  schedule:
    - cron: "0 0 * * 0"   # Runs every Sunday at 00:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  update-activity:
    name: Update Recent Activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update activity in README
        uses: Readme-Workflows/recent-activity@v2.6.0
        with:
          GH_USERNAME: Old-Daoist

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated GitHub activity"
